version: '3'
services:
  ask_me_bot:
    container_name: ask_me_bot
    restart: always
    image: ghcr.io/ourneu-space/ask_me_bot:latest
    networks:
      - external_network
    volumes:
      - ./app:/app
    ports:
      - '127.0.0.1:5000:5000'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5000/"]
      interval: 10s    
  
networks:
  external_network: