name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Log in to the Github Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name != 'pull_request'

    - name: Build and push
      uses: docker/build-push-action@v2.7.0
      with:
        context: .
        platforms: linux/amd64,linux/arm64/v8
        push: true
        tags: ghcr.io/ourneu-space/spark-dependencies:$(date +%s)
