name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Log in to the Github Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name != 'pull_request'

    - uses: docker/metadata-action@v4
      id: meta
      with:
        images: ghcr.io/${{ github.repository_owner }}/ask_me_bot
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=edge,branch=master
          type=sha,prefix=,format=long

    - uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
